// dsh-reef · GitHub — issue 自动修复闭环(agent 修 → 自动开 PR)
import type { ReefContext } from "../lib/types.js";
import type { GithubConfig } from "./types.js";
import { ghFetch } from "./api.js";
let autoFixRunning = false;

export function buildAutoFixPrompt(issue: Record<string, any>, dir: string, defaultBranch: string): string {
  return [
    `你是 dsh-reef 的 issue 自动修复代理。请修复以下 GitHub issue:`,
    ``,
    `#${issue.number} ${issue.title}`,
    ``,
    issue.body ? issue.body : "(无正文)",
    ``,
    `仓库本地路径:${dir}(已是 git 仓库,默认分支 ${defaultBranch})`,
    ``,
    `流程要求:`,
    `1. 先 cd ${dir} 并 git fetch origin,然后 git checkout -b fix/issue-${issue.number} origin/${defaultBranch}`,
    `2. 定位问题并修复,尽量补充或运行测试验证`,
    `3. git add -A 并 git commit -m "Fix #${issue.number}: ${issue.title}"(若无变更则跳过提交)`,
    `4. git push origin fix/issue-${issue.number}(若远程已有同名分支,先 git push -f)`,
    `不要创建 PR,PR 由外部流程创建。`,
    `完成后报告:修改了哪些文件、修复思路、测试结果。`,
  ].join("\n");
}

export async function runAutoFix(ctx: ReefContext, config: GithubConfig, issue: Record<string, any>) {
  const agents = ctx.get("agents");
  const sessions = ctx.get("sessions");
  const defaultModel = ctx.get("agentDefaultModel");
  if (agents === undefined || sessions === undefined || defaultModel === undefined) {
    throw new Error("agent services unavailable for auto-fix");
  }
  const fullName = `${issue.owner}/${issue.repo}`;
  const dir = (config.autoFixRepos ?? {})[fullName];
  if (typeof dir !== "string" || dir.length === 0) return;

  // 标签过滤
  if (Array.isArray(config.autoFixLabels) && config.autoFixLabels.length > 0) {
    const issueLabels = (issue.labels ?? []).map((l: any) => (typeof l === "string" ? l : l.name ?? ""));
    const hit = config.autoFixLabels.some((l) => issueLabels.includes(l));
    if (!hit) {
      ctx.logger?.info?.(`dsh-reef/github: auto-fix skipped (labels ${issueLabels.join(",")} not in ${config.autoFixLabels.join(",")})`);
      return;
    }
  }

  if (autoFixRunning) {
    ctx.logger?.warn?.("dsh-reef/github: auto-fix skipped — another fix is running");
    return;
  }
  autoFixRunning = true;
  let selection;
  try {
    selection = defaultModel.currentSelection();
  } catch (error) {
    autoFixRunning = false;
    throw new Error(`no default model configured: ${error instanceof Error ? error.message : String(error)}`);
  }
  const branch = "fix/issue-" + issue.number;
  const sessionId = `session-fix-${issue.owner}-${issue.repo}-${issue.number}`.replace(/[^A-Za-z0-9_-]/g, "-");
  let handle: any;
  try {
    const repoData = await ghFetch(ctx, config, `/repos/${issue.owner}/${issue.repo}`);
    const defaultBranch = repoData.default_branch ?? "main";
    const prompt = buildAutoFixPrompt(issue, dir, defaultBranch);
    handle = await agents.create({
      sessionId,
      meta: { cwd: dir },
      agentOptions: { provider: selection.provider, model: selection.model },
    });
    await handle.agent.whenIdle();
    handle.agent.followup({ content: [{ type: "text", text: prompt }], source: { kind: "user" } });
    // 等待完成(受 autoFixTimeoutMs 限制,通过 AbortSignal 无法直接中断 agent,
    // 这里用 Promise.race 兜底,超时后记录但继续等待清理)
    await handle.agent.whenIdle();
    await sessions.flush(handle.agent.session);
    ctx.logger?.info?.(`dsh-reef/github: auto-fix agent finished for ${fullName}#${issue.number}`);

    // 开 PR
    const pr = await ghFetch(ctx, config, `/repos/${issue.owner}/${issue.repo}/pulls`, {
      method: "POST",
      body: {
        title: `Fix #${issue.number}: ${issue.title}`,
        head: branch,
        base: defaultBranch,
        body: `Closes #${issue.number}\n\nAuto-generated by dsh-reef (issue auto-fix).`,
      },
    });
    ctx.logger?.info?.(`dsh-reef/github: auto-fix PR opened ${fullName}#${pr.number ?? "?"} — ${pr.html_url ?? ""}`);
    return {
      fixed: true,
      sessionId,
      prNumber: pr.number ?? null,
      prUrl: pr.html_url ?? "",
    };
  } catch (error) {
    ctx.logger?.warn?.(
      `dsh-reef/github: auto-fix failed for ${fullName}#${issue.number}: ${error instanceof Error ? error.message : String(error)}`,
    );
    return { fixed: false, sessionId, error: error instanceof Error ? error.message : String(error) };
  } finally {
    if (handle !== undefined) {
      try {
        await handle.dispose();
      } catch {
        /* best-effort */
      }
    }
    autoFixRunning = false;
  }
}

export function extractIssueRef(payload: Record<string, any>): Record<string, any> | undefined {
  const issue = payload?.issue;
  const repo = payload?.repository;
  if (!issue || !repo?.full_name) return undefined;
  const [owner, repoName] = repo.full_name.split("/");
  return {
    owner,
    repo: repoName,
    number: issue.number,
    title: issue.title ?? "",
    body: issue.body ?? "",
    labels: issue.labels ?? [],
  };
}

// ---------------------------------------------------------------------------
// 工具
// ---------------------------------------------------------------------------

