import { installSettingsSection, settingsNamespace } from "@deepseek-ai/dsh-settings";
import z from "schemastery";
import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { chmod, copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { isAbsolute, join } from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
/** Default GUI URL. */
const DEFAULT_URL = "http://127.0.0.1:3080";
/**
* Fill defaults from a partial config (schema defaults may be absent in
* hand-built test contexts). An empty profile means "no --profile flag".
* @param config - partial launcher config.
* @returns the resolved spec.
*/
function resolveLauncherSpec(config) {
	return {
		dshCommand: config.dshCommand ?? "dsh",
		url: config.url ?? "http://127.0.0.1:3080",
		...config.profile === void 0 || config.profile === "" ? {} : { profile: config.profile },
		...config.iconPath === void 0 || config.iconPath === "" ? {} : { iconPath: config.iconPath }
	};
}
/** File name of the launcher script under ~/.dsh/desktop-launcher/. */
function scriptFileName(platform) {
	switch (platform) {
		case "win32": return "launcher.ps1";
		case "darwin": return "launcher.command";
		case "linux": return "launcher.sh";
	}
}
/** File name of the silent boot-autostart script under ~/.dsh/desktop-launcher/. */
function autostartFileName(platform) {
	switch (platform) {
		case "win32": return "autostart.ps1";
		case "darwin": return "autostart.command";
		case "linux": return "autostart.sh";
	}
}
/** File name of the icon placed on the Desktop. */
function desktopFileName(platform) {
	switch (platform) {
		case "win32": return "DeepSeek-Harness.lnk";
		case "darwin": return "DeepSeek-Harness.command";
		case "linux": return "deepseek-harness.desktop";
	}
}
/** Single-quote a value for PowerShell (embedded quotes are doubled). */
function psSingle(value) {
	return `'${value.replaceAll("'", "''")}'`;
}
/** Single-quote a value for POSIX sh (embedded quotes are escaped). */
function shSingle(value) {
	return `'${value.replaceAll("'", "'\\''")}'`;
}
/**
 * Shared PowerShell prologue: spec-derived probe constants plus the
 * two-stage readiness probe. Stage 1 is a raw TCP connect — immune to
 * system-proxy state, which is what broke boot launches before: a proxy
 * client that was not ready yet made an HTTP-only probe fail, so a second
 * dsh web got spawned and crashed with EADDRINUSE while the first one held
 * the port without serving. Stage 2 is HTTP readiness with an explicit null
 * proxy so localhost never rides a system proxy regardless of configuration.
 */
const POWERSHELL_PROBE_LINES = [
	"$uri = [Uri]$url",
	"$probeHost = $uri.Host",
	"$probePort = $uri.Port",
	"",
	"function Test-DshPort {",
	"  $client = New-Object System.Net.Sockets.TcpClient",
	"  try {",
	"    $connect = $client.ConnectAsync($probeHost, $probePort)",
	"    if (-not $connect.Wait(800)) { return $false }",
	"    return $client.Connected",
	"  } catch {",
	"    return $false",
	"  } finally {",
	"    $client.Dispose()",
	"  }",
	"}",
	"",
	"function Test-DshHttp {",
	"  try {",
	"    $request = [System.Net.HttpWebRequest]::Create($url)",
	"    $request.Proxy = $null",
	"    $request.Timeout = 2000",
	"    $request.ReadWriteTimeout = 2000",
	"    $response = $request.GetResponse()",
	"    $code = [int]$response.StatusCode",
	"    $response.Close()",
	"    return $code -ge 200 -and $code -lt 500",
	"  } catch {",
	"    return $false",
	"  }",
	"}"
];
/** PowerShell launcher: probes the URL, starts dsh hidden, polls, opens the GUI. */
/** PowerShell launcher: shows a DeepSeek Harness styled popup while it probes, starts dsh hidden, waits for the GUI. */
function renderPowerShell(spec) {
	return [
		"# DeepSeek Harness launcher (generated by dsh-desktop-launcher)",
		"$ErrorActionPreference = 'SilentlyContinue'",
		`$dshCommand = ${psSingle(spec.dshCommand)}`,
		`$url = ${psSingle(spec.url)}`,
		`$profile = ${psSingle(spec.profile ?? "")}`,
		...POWERSHELL_PROBE_LINES,
		"",
		"if (Test-DshHttp) {",
		"  Start-Process $url",
		"  exit 0",
		"}",
		"",
		"$command = Get-Command $dshCommand -ErrorAction SilentlyContinue",
		"$dshMissing = ($null -eq $command)",
		"",
		"# ---- startup popup: borderless WPF window in DeepSeek Harness style ----",
		"Add-Type -AssemblyName PresentationFramework",
		"[xml]$popupXaml = @'",
		"<Window xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"",
		"        Width=\"400\" SizeToContent=\"Height\" WindowStyle=\"None\"",
		"        AllowsTransparency=\"True\" Background=\"Transparent\" ShowInTaskbar=\"False\"",
		"        Topmost=\"True\" WindowStartupLocation=\"CenterScreen\">",
		"  <Border CornerRadius=\"16\" Background=\"#1B1E27\" Padding=\"22,20\">",
		"    <Border.Effect>",
		"      <DropShadowEffect Color=\"#000000\" BlurRadius=\"26\" ShadowDepth=\"0\" Opacity=\"0.5\"/>",
		"    </Border.Effect>",
		"    <StackPanel Orientation=\"Horizontal\">",
		"      <Border Width=\"56\" Height=\"56\" CornerRadius=\"14\" Background=\"#FFFFFF\" VerticalAlignment=\"Center\">",
		"        <Image x:Name=\"IconImage\" Width=\"56\" Height=\"56\" Stretch=\"Uniform\"/>",
		"      </Border>",
		"      <StackPanel Margin=\"16,0,0,0\" VerticalAlignment=\"Center\">",
		"        <TextBlock Text=\"DeepSeek Harness\" FontSize=\"16\" FontWeight=\"SemiBold\" Foreground=\"#F2F3F5\"/>",
		"        <StackPanel Orientation=\"Horizontal\" Margin=\"0,7,0,0\">",
		"          <Ellipse x:Name=\"Spinner\" Width=\"14\" Height=\"14\" Stroke=\"#4D6BFE\" StrokeThickness=\"2\"",
		"                   StrokeDashArray=\"1.6 2.4\" RenderTransformOrigin=\"0.5,0.5\">",
		"            <Ellipse.RenderTransform>",
		"              <RotateTransform x:Name=\"SpinnerRotate\" Angle=\"0\"/>",
		"            </Ellipse.RenderTransform>",
		"            <Ellipse.Triggers>",
		"              <EventTrigger RoutedEvent=\"Ellipse.Loaded\">",
		"                <BeginStoryboard>",
		"                  <Storyboard RepeatBehavior=\"Forever\">",
		"                    <DoubleAnimation Storyboard.TargetName=\"SpinnerRotate\" Storyboard.TargetProperty=\"Angle\"",
		"                                     From=\"0\" To=\"360\" Duration=\"0:0:0.9\"/>",
		"                  </Storyboard>",
		"                </BeginStoryboard>",
		"              </EventTrigger>",
		"            </Ellipse.Triggers>",
		"          </Ellipse>",
		"          <TextBlock x:Name=\"StatusText\" Text=\"正在启动…\" FontSize=\"12\" Foreground=\"#9BA1B0\"",
		"                     Margin=\"9,0,0,0\" VerticalAlignment=\"Center\"/>",
		"        </StackPanel>",
		"        <TextBlock x:Name=\"DetailText\" Text=\"正在准备环境\" FontSize=\"11\" Foreground=\"#6B7280\"",
		"                   Margin=\"0,5,0,0\" TextWrapping=\"Wrap\" MaxWidth=\"280\"/>",
		"        <Button x:Name=\"CloseButton\" Content=\"确定\" Visibility=\"Collapsed\" Margin=\"0,10,0,0\"",
		"                HorizontalAlignment=\"Left\" Padding=\"14,5\" FontSize=\"12\" Foreground=\"#FFFFFF\"",
		"                Background=\"#4D6BFE\" BorderThickness=\"0\" Cursor=\"Hand\">",
		"          <Button.Resources>",
		"            <Style TargetType=\"Button\">",
		"              <Setter Property=\"Template\">",
		"                <Setter.Value>",
		"                  <ControlTemplate TargetType=\"Button\">",
		"                    <Border x:Name=\"Bd\" Background=\"{TemplateBinding Background}\" CornerRadius=\"8\"",
		"                            Padding=\"{TemplateBinding Padding}\">",
		"                      <ContentPresenter HorizontalAlignment=\"Center\" VerticalAlignment=\"Center\"/>",
		"                    </Border>",
		"                    <ControlTemplate.Triggers>",
		"                      <Trigger Property=\"IsMouseOver\" Value=\"True\">",
		"                        <Setter TargetName=\"Bd\" Property=\"Background\" Value=\"#5B77FF\"/>",
		"                      </Trigger>",
		"                    </ControlTemplate.Triggers>",
		"                  </ControlTemplate>",
		"                </Setter.Value>",
		"              </Setter>",
		"            </Style>",
		"          </Button.Resources>",
		"        </Button>",
		"      </StackPanel>",
		"    </StackPanel>",
		"  </Border>",
		"</Window>",
		"'@",
		"",
		"$popup = [System.Windows.Markup.XamlReader]::Load((New-Object System.Xml.XmlNodeReader $popupXaml))",
		"$iconImage = $popup.FindName('IconImage')",
		"$iconPath = Join-Path $PSScriptRoot 'dsh.png'",
		"if (-not (Test-Path $iconPath)) { $iconPath = Join-Path $PSScriptRoot 'dsh.ico' }",
		"if (Test-Path $iconPath) { $iconImage.Source = New-Object System.Windows.Media.Imaging.BitmapImage([uri]$iconPath) }",
		"$statusText = $popup.FindName('StatusText')",
		"$detailText = $popup.FindName('DetailText')",
		"$closeButton = $popup.FindName('CloseButton')",
		"",
		"function Pump-Popup {",
		"  [System.Windows.Threading.Dispatcher]::CurrentDispatcher.Invoke([Action]{}, [System.Windows.Threading.DispatcherPriority]::Background) | Out-Null",
		"}",
		"",
		"$closeButton.Add_Click({ $popup.Close() })",
		"",
		"function Show-PopupError($status, $detail) {",
		"  $statusText.Text = $status",
		"  $statusText.Foreground = New-Object System.Windows.Media.SolidColorBrush([System.Windows.Media.Color]::FromRgb(0xE5, 0x4D, 0x4D))",
		"  $detailText.Text = $detail",
		"  $closeButton.Visibility = 'Visible'",
		"  $popup.Show()",
		"  while ($popup.IsVisible) {",
		"    Start-Sleep -Milliseconds 100",
		"    Pump-Popup",
		"  }",
		"}",
		"",
		"if ($dshMissing) {",
		"  Show-PopupError '启动失败' (\"找不到 dsh 命令：\" + $dshCommand)",
		"  exit 1",
		"}",
		"",
		"$popup.Show()",
		"",
		"# Single-instance guard: when something already holds the port, spawning a",
		"# second dsh web would die with EADDRINUSE and leave nothing serving.",
		"if (Test-DshPort) {",
		"  $deadline = (Get-Date).AddSeconds(45)",
		"  while ((Get-Date) -lt $deadline) {",
		"    Start-Sleep -Milliseconds 250",
		"    Pump-Popup",
		"    if (Test-DshHttp) {",
		"      $statusText.Text = '启动完成'",
		"      Pump-Popup",
		"      Start-Sleep -Milliseconds 300",
		"      $popup.Close()",
		"      Start-Process $url",
		"      exit 0",
		"    }",
		"  }",
		"  Show-PopupError '启动失败' (\"端口 $probePort 已被占用但服务未就绪：可能存在残留的 dsh web 进程，请先结束它再重试。\")",
		"  exit 1",
		"}",
		"",
		"$arguments = @('web')",
		"if ($profile -ne '') {",
		"  $arguments += @('--profile', $profile)",
		"}",
		"Start-Process -FilePath $command.Source -ArgumentList $arguments -WindowStyle Hidden",
		"",
		"$deadline = (Get-Date).AddSeconds(90)",
		"while ((Get-Date) -lt $deadline) {",
		"  Start-Sleep -Milliseconds 250",
		"  Pump-Popup",
		"  if (Test-DshHttp) {",
		"    $statusText.Text = '启动完成'",
		"    $detailText.Text = '正在打开浏览器…'",
		"    Pump-Popup",
		"    Start-Sleep -Milliseconds 400",
		"    $popup.Close()",
		"    Start-Process $url",
		"    exit 0",
		"  }",
		"}",
		"Show-PopupError '启动超时' (\"90 秒内未就绪：\" + $url)",
		"exit 1",
		""
	].join("\n");
}
/** POSIX launcher (macOS .command / Linux .sh) with the platform open command. */
function renderPosix(platform, spec) {
	const open = platform === "darwin" ? "open" : "xdg-open";
	const alert = platform === "darwin" ? "osascript -e 'display dialog \"dsh command not found: '\"$DASH\"'\" with title \"DSH Launcher\" with icon caution' 2>/dev/null || echo \"dsh command not found: $DASH\" >&2" : "zenity --error --title=\"DSH Launcher\" --text=\"dsh command not found: $DASH\" 2>/dev/null || echo \"dsh command not found: $DASH\" >&2";
	return [
		"#!/bin/bash",
		"# DSH web launcher (generated by dsh-desktop-launcher)",
		`DASH=${shSingle(spec.dshCommand)}`,
		`URL=${shSingle(spec.url)}`,
		`PROFILE=${shSingle(spec.profile ?? "")}`,
		"",
		"probe() {",
		"  curl --noproxy \"*\" -fsS --max-time 2 \"$URL\" >/dev/null 2>&1",
		"}",
		"",
		"if probe; then",
		`  ${open} "$URL"`,
		"  exit 0",
		"fi",
		"",
		"if ! command -v \"$DASH\" >/dev/null 2>&1; then",
		`  ${alert}`,
		"  exit 1",
		"fi",
		"",
		"if [ -n \"$PROFILE\" ]; then",
		"  \"$DASH\" web --profile \"$PROFILE\" >/dev/null 2>&1 &",
		"else",
		"  \"$DASH\" web >/dev/null 2>&1 &",
		"fi",
		"",
		"for i in $(seq 1 180); do",
		"  if probe; then",
		`    ${open} "$URL"`,
		"    exit 0",
		"  fi",
		"  sleep 0.5",
		"done",
		"",
		"echo \"dsh web did not start within 90 seconds: $URL\" >&2",
		"exit 1",
		""
	].join("\n");
}
/**
 * Render the silent boot-autostart body for Windows: no popup, a bounded
 * append-only log next to the script, an explicit embedded DSH_HOME so a
 * portable home keeps working from a bare login environment, the same
 * single-instance guard as the interactive launcher, and one optional
 * browser tab once the server is actually ready.
 */
function renderWindowsAutostart(spec, dshHome) {
	return [
		"# DeepSeek Harness autostart (generated by dsh-desktop-launcher)",
		"# Silent boot variant of launcher.ps1: no popup, appends to autostart.log.",
		"$ErrorActionPreference = 'SilentlyContinue'",
		`$dshCommand = ${psSingle(spec.dshCommand)}`,
		`$url = ${psSingle(spec.url)}`,
		`$profile = ${psSingle(spec.profile ?? "")}`,
		`$dshHome = ${psSingle(dshHome)}`,
		"$openBrowser = $true",
		"$waitSeconds = 120",
		"$logFile = Join-Path $PSScriptRoot 'autostart.log'",
		...POWERSHELL_PROBE_LINES,
		"",
		"function Write-Log($message) {",
		"  try {",
		"    $line = \"[{0}] {1}\" -f (Get-Date -Format \"yyyy-MM-dd HH:mm:ss\"), $message",
		"    Add-Content -LiteralPath $logFile -Value $line -Encoding UTF8",
		"    $item = Get-Item -LiteralPath $logFile -ErrorAction SilentlyContinue",
		"    if ($item -and $item.Length -gt 262144) {",
		"      $tail = Get-Content -LiteralPath $logFile -Tail 200 -Encoding UTF8",
		"      Set-Content -LiteralPath $logFile -Value $tail -Encoding UTF8",
		"    }",
		"  } catch {}",
		"}",
		"",
		"# A portable DSH_HOME must survive a bare login environment: embed the",
		"# value the running host actually used instead of trusting ambient state.",
		"if ($dshHome -ne '') { $env:DSH_HOME = $dshHome }",
		"Write-Log (\"autostart tick: url=\" + $url)",
		"",
		"if (Test-DshHttp) {",
		"  Write-Log \"already serving; nothing to do\"",
		"  if ($openBrowser) { Start-Process $url }",
		"  exit 0",
		"}",
		"",
		"# Port held by someone not serving yet: wait instead of spawning a",
		"# duplicate that would crash with EADDRINUSE.",
		"if (Test-DshPort) {",
		"  Write-Log (\"port \" + $probePort + \" already held; waiting for readiness\")",
		"  $deadline = (Get-Date).AddSeconds(60)",
		"  while ((Get-Date) -lt $deadline) {",
		"    Start-Sleep -Milliseconds 500",
		"    if (Test-DshHttp) {",
		"      Write-Log \"holder became ready\"",
		"      if ($openBrowser) { Start-Process $url }",
		"      exit 0",
		"    }",
		"  }",
		"  Write-Log \"ERROR: port held but never became ready; not spawning a second instance\"",
		"  exit 1",
		"}",
		"",
		"$command = Get-Command $dshCommand -ErrorAction SilentlyContinue",
		"if ($null -eq $command) {",
		"  Write-Log (\"ERROR: dsh command not found: \" + $dshCommand)",
		"  exit 1",
		"}",
		"",
		"$arguments = @('web')",
		"if ($profile -ne '') {",
		"  $arguments += @('--profile', $profile)",
		"}",
		"Write-Log (\"spawning: \" + $command.Source + \" \" + ($arguments -join \" \"))",
		"$spawned = Start-Process -FilePath $command.Source -ArgumentList $arguments -WindowStyle Hidden -PassThru",
		"if ($spawned) { Write-Log (\"spawned pid \" + $spawned.Id) }",
		"",
		"$deadline = (Get-Date).AddSeconds($waitSeconds)",
		"while ((Get-Date) -lt $deadline) {",
		"  Start-Sleep -Milliseconds 500",
		"  if (Test-DshHttp) {",
		"    Write-Log \"ready\"",
		"    if ($openBrowser) { Start-Process $url }",
		"    exit 0",
		"  }",
		"}",
		"Write-Log (\"ERROR: not ready within \" + $waitSeconds + \" seconds\")",
		"exit 1",
		""
	].join("\n");
}
/** POSIX autostart body shared by macOS and Linux (curl with proxies disabled). */
function renderPosixAutostart(platform, spec) {
	const open = platform === "darwin" ? "open" : "xdg-open";
	return [
		"#!/bin/bash",
		"# DeepSeek Harness autostart (generated by dsh-desktop-launcher)",
		`DASH=${shSingle(spec.dshCommand)}`,
		`URL=${shSingle(spec.url)}`,
		`PROFILE=${shSingle(spec.profile ?? "")}`,
		"OPEN_BROWSER=yes",
		"LOG_FILE=\"$(dirname \"$0\")/autostart.log\"",
		"",
		"log() { echo \"[$(date '+%Y-%m-%d %H:%M:%S')] $*\" >> \"$LOG_FILE\"; }",
		"probe_http() { curl --noproxy \"*\" -fsS --max-time 2 \"$URL\" >/dev/null 2>&1; }",
		"",
		"log \"autostart tick: url=$URL\"",
		"if probe_http; then",
		"  log \"already serving; nothing to do\"",
		"  if [ \"$OPEN_BROWSER\" = yes ]; then \"$open\" \"$URL\"; fi",
		"  exit 0",
		"fi",
		"if command -v lsof >/dev/null 2>&1 && echo \"$URL\" | grep -qE \":[0-9]+$\"; then",
		"  PORT=\"${URL##*:}\"",
		"  if lsof -iTCP:\"$PORT\" -sTCP:LISTEN >/dev/null 2>&1; then",
		"    log \"port $PORT already held; waiting for readiness\"",
		"    for i in $(seq 1 120); do",
		"      sleep 0.5",
		"      if probe_http; then",
		"        log \"holder became ready\"",
		"        if [ \"$OPEN_BROWSER\" = yes ]; then \"$open\" \"$URL\"; fi",
		"        exit 0",
		"      fi",
		"    done",
		"    log \"ERROR: port held but never became ready\"",
		"    exit 1",
		"  fi",
		"fi",
		"if ! command -v \"$DASH\" >/dev/null 2>&1; then",
		"  log \"ERROR: dsh command not found: $DASH\"",
		"  exit 1",
		"fi",
		"if [ -n \"$PROFILE\" ]; then",
		"  \"$DASH\" web --profile \"$PROFILE\" >/dev/null 2>&1 &",
		"else",
		"  \"$DASH\" web >/dev/null 2>&1 &",
		"fi",
		"for i in $(seq 1 240); do",
		"  if probe_http; then",
		"    log \"ready\"",
		"    if [ \"$OPEN_BROWSER\" = yes ]; then \"$open\" \"$URL\"; fi",
		"    exit 0",
		"  fi",
		"  sleep 0.5",
		"done",
		"log \"ERROR: not ready within 120 seconds\"",
		"exit 1",
		""
	].join("\n");
}
/**
 * Render the silent boot-autostart body for one platform.
 * @param platform - target desktop platform.
 * @param spec - resolved launcher behavior.
 * @param dshHome - DSH_HOME to embed (used on win32 only).
 * @returns the autostart script body.
 */
function renderAutostartScript(platform, spec, dshHome) {
	switch (platform) {
		case "win32": return renderWindowsAutostart(spec, dshHome);
		case "darwin":
		case "linux": return renderPosixAutostart(platform, spec);
	}
}
/**
* Render the launcher script for one platform.
* @param platform - target desktop platform.
* @param spec - resolved launcher behavior.
* @returns the script body.
*/
function renderLauncherScript(platform, spec) {
	switch (platform) {
		case "win32": return renderPowerShell(spec);
		case "darwin":
		case "linux": return renderPosix(platform, spec);
	}
}
/**
* Render the Linux desktop entry (the macOS launcher doubles as the desktop
* file; Windows uses a .lnk created by the installer script).
* @param launcherPath - absolute path of the launcher script.
* @returns the .desktop file body.
*/
function renderDesktopEntry(launcherPath, iconPath) {
	const iconLine = iconPath === void 0 ? "Icon=utilities-terminal" : `Icon=${iconPath}`;
	return [
		"[Desktop Entry]",
		"Type=Application",
		"Version=1.0",
		"Name=DeepSeek Harness",
		"Comment=Launch DeepSeek Harness Web GUI",
		`Exec="${launcherPath}"`,
		iconLine,
		"Terminal=true",
		"Categories=Development;",
		""
	].join("\n");
}
/**
* Render the Windows shortcut installer: a PowerShell script that creates
* the Desktop .lnk pointing at the launcher.ps1, run hidden by the host.
* @param opts - the launcher, icon, and working-directory paths.
* @returns the installer body.
*/
function renderShortcutInstaller(opts) {
	const { launcherPath, desktopPath, homeDir, iconLocation } = opts;
	return [
		"# DSH desktop shortcut installer (generated by dsh-desktop-launcher)",
		"$ErrorActionPreference = 'Stop'",
		"$ws = New-Object -ComObject WScript.Shell",
		`$shortcut = $ws.CreateShortcut(${psSingle(desktopPath)})`,
		`$shortcut.TargetPath = ${psSingle("powershell.exe")}`,
		`$shortcut.Arguments = ${psSingle(`-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ${launcherPath}`)}`,
		`$shortcut.WorkingDirectory = ${psSingle(homeDir)}`,
		`$shortcut.IconLocation = ${psSingle(iconLocation)}`,
		`$shortcut.Description = ${psSingle("Launch DeepSeek Harness Web GUI")}`,
		"$shortcut.Save()",
		""
	].join("\n");
}
/** Where the per-user boot-autostart entry lives for one platform. */
function autostartDir(platform, home) {
	switch (platform) {
		case "win32": {
			const appdata = process.env.APPDATA && process.env.APPDATA.trim() !== "" ? process.env.APPDATA : `${home}\\AppData\\Roaming`;
			return `${appdata}\\Microsoft\\Windows\\Start Menu\\Programs\\Startup`;
		}
		case "darwin": return `${home}/Library/LaunchAgents`;
		case "linux": return `${home}/.config/autostart`;
	}
}
/**
 * The user-visible autostart entry name: a Startup-folder .lnk on Windows,
 * a LaunchAgent plist on macOS, an XDG autostart .desktop on Linux.
 */
function autostartEntryName(platform) {
	switch (platform) {
		case "win32": return "DeepSeek-Harness.lnk";
		case "darwin": return "com.deepseek-harness.web.plist";
		case "linux": return "deepseek-harness-autostart.desktop";
	}
}
/** Full path of the autostart entry for one platform and home. */
function autostartEntryPath(platform, home) {
	const separator = platform === "win32" ? "\\" : "/";
	return `${autostartDir(platform, home)}${separator}${autostartEntryName(platform)}`;
}
/**
 * Render the Windows autostart installer: a PowerShell script that creates
 * the Startup-folder .lnk pointing at the silent autostart.ps1, run hidden
 * by the host. Same COM mechanism as the desktop shortcut installer.
 */
function renderAutostartInstaller(opts) {
	const { autostartScriptPath, entryPath, homeDir, iconLocation } = opts;
	return [
		"# DSH autostart installer (generated by dsh-desktop-launcher)",
		"$ErrorActionPreference = 'Stop'",
		"$ws = New-Object -ComObject WScript.Shell",
		`$shortcut = $ws.CreateShortcut(${psSingle(entryPath)})`,
		`$shortcut.TargetPath = ${psSingle("powershell.exe")}`,
		`$shortcut.Arguments = ${psSingle(`-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ${autostartScriptPath}`)}`,
		`$shortcut.WorkingDirectory = ${psSingle(homeDir)}`,
		`$shortcut.IconLocation = ${psSingle(iconLocation)}`,
		`$shortcut.Description = ${psSingle("Start DeepSeek Harness Web GUI at login")}`,
		"$shortcut.Save()",
		""
	].join("\n");
}
/**
 * Render the macOS LaunchAgent plist body running the silent script at
 * login (Aqua session).
 */
function renderAutostartPlist(autostartScriptPath, logPath) {
	return [
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
		"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
		"<plist version=\"1.0\">",
		"<dict>",
		"  <key>Label</key>",
		"  <string>com.deepseek-harness.web</string>",
		"  <key>ProgramArguments</key>",
		"  <array>",
		"    <string>/bin/bash</string>",
		`    <string>${autostartScriptPath}</string>`,
		"  </array>",
		"  <key>RunAtLoad</key>",
		"  <true/>",
		"  <key>StandardOutPath</key>",
		`  <string>${logPath}</string>`,
		"  <key>StandardErrorPath</key>",
		`  <string>${logPath}</string>`,
		"</dict>",
		"</plist>",
		""
	].join("\n");
}
/**
 * Render the Linux XDG autostart desktop entry running the silent script.
 */
function renderAutostartDesktopEntry(autostartScriptPath) {
	return [
		"[Desktop Entry]",
		"Type=Application",
		"Version=1.0",
		"Name=DeepSeek Harness",
		"Comment=Start DeepSeek Harness Web GUI at login",
		`Exec="${autostartScriptPath}"`,
		"Terminal=false",
		"X-GNOME-Autostart-enabled=true",
		"Categories=Development;",
		""
	].join("\n");
}
//#endregion
//#region src/protocol.ts
/** Route family of the desktop-launcher host API. */
const LAUNCHER_API = {
	/** Create (or refresh) the desktop icon. */
	create: "/api/dsh-desktop-launcher/create",
	/** Request the host process to exit gracefully. */
	shutdown: "/api/dsh-desktop-launcher/shutdown",
	/** Query or toggle boot autostart registration. */
	autostart: "/api/dsh-desktop-launcher/autostart"
};
//#endregion
//#region src/loopback.ts
/** IPv4 127/8 predicate (four decimal octets, first == 127). */
function isIPv4Loopback(v4) {
	const parts = v4.split(".");
	return parts.length === 4 && parts[0] === "127" && parts.every((part) => /^\d{1,3}$/.test(part) && Number(part) <= 255);
}
/** Whether a socket remote address names the loopback range (127/8, ::1, IPv4-mapped). */
function isLoopbackAddress(address) {
	if (address === void 0) return false;
	const normalized = address.toLowerCase();
	if (normalized === "::1") return true;
	if (normalized.startsWith("::ffff:")) return isIPv4Loopback(normalized.slice(7));
	return isIPv4Loopback(normalized);
}
/** Whether a normalized URL hostname names the loopback authority (localhost, [::1], 127/8). */
function isLoopbackHostname(hostname) {
	if (hostname === "localhost" || hostname === "[::1]") return true;
	return isIPv4Loopback(hostname);
}
/**
* Request-level trust fence: a loopback socket address AND a loopback Host
* header, plus browser same-origin markers. The socket address is
* authoritative; X-Forwarded-For is never trusted.
*/
function isLoopbackRequest(request) {
	if (!isLoopbackAddress(request.socket.remoteAddress)) return false;
	const host = request.headers.host;
	if (typeof host !== "string") return false;
	let hostUrl;
	try {
		hostUrl = new URL("http://" + host);
	} catch {
		return false;
	}
	if (!isLoopbackHostname(hostUrl.hostname)) return false;
	if (request.headers["sec-fetch-site"] === "cross-site") return false;
	const origin = request.headers.origin;
	if (origin === void 0) return true;
	try {
		return new URL(origin).host === hostUrl.host;
	} catch {
		return false;
	}
}
//#endregion
//#region src/routes.ts
/**
* The /api/dsh-desktop-launcher route family: one POST that writes the
* launcher script under ~/.dsh/desktop-launcher/ and places the double-click
* icon on the Desktop. Every route carries the same loopback-only trust
* fence as the dsh-ssh routes — this endpoint writes files on the host
* machine, so LAN-exposed dsh web deployments must not serve it.
*/
const execFileAsync = promisify(execFile);
/** One JSON response. */
function writeJson$1(res, status, body) {
	const payload = JSON.stringify(body);
	res.writeHead(status, {
		"content-type": "application/json; charset=utf-8",
		"referrer-policy": "no-referrer"
	});
	res.end(payload);
}
/**
* The dsh icon bundled with the package (assets/dsh.ico next to lib/index.js).
* Vitest transforms src modules to non-file URLs, so a missing or unparsable
* bundle URL is tolerated (tests inject iconSource instead).
*/
let bundledIconPath;
let bundledPngPath;
if (import.meta.url.startsWith("file:")) {
	try {
		bundledIconPath = fileURLToPath(new URL("../assets/dsh.ico", import.meta.url));
	} catch {}
	try {
		bundledPngPath = fileURLToPath(new URL("../assets/dsh.png", import.meta.url));
	} catch {}
}
/**
* Resolve the icon source: the injected override, then the configured
* iconPath when it exists, then the bundled dsh icon. Undefined when none is
* available.
* @param configured - the spec's optional iconPath.
* @param override - test seam: an explicit icon file.
* @returns the source icon file, or undefined.
*/
function resolveIconSource(configured, override) {
	if (override !== void 0 && existsSync(override)) return override;
	if (configured !== void 0 && configured !== "" && existsSync(configured)) return configured;
	return bundledIconPath !== void 0 && existsSync(bundledIconPath) ? bundledIconPath : void 0;
}
/** Default runner: execFile with a 30s cap, reporting exit code and stderr. */
const defaultRunner = async (file, args) => {
	try {
		await execFileAsync(file, args, {
			timeout: 3e4,
			windowsHide: true
		});
		return {
			code: 0,
			stderr: ""
		};
	} catch (error) {
		const code = typeof error === "object" && error !== null && "code" in error ? error.code : null;
		return {
			code: typeof code === "number" ? code : null,
			stderr: error instanceof Error ? error.message : String(error)
		};
	}
};
/** Narrow a raw platform string to the supported set. */
function toLauncherPlatform(platform) {
	if (platform === "win32" || platform === "darwin" || platform === "linux") return platform;
	throw new Error(`unsupported platform: ${platform}`);
}
/**
* Desktop directory: the standard Desktop, with the OneDrive redirect
* fallback on Windows when the plain path does not exist.
*/
function resolveDesktopDir(home, platform) {
	const desktop = join(home, "Desktop");
	if (platform === "win32" && !existsSync(desktop)) {
		const onedrive = join(home, "OneDrive", "Desktop");
		if (existsSync(onedrive)) return onedrive;
	}
	return desktop;
}
/**
* Best-effort dsh command probe (never throws). Absolute or path-like
* commands are checked by existence; bare names are probed through the
* platform's PATH lookup.
*/
async function probeDsh(platform, run, dshCommand) {
	if (isAbsolute(dshCommand) || dshCommand.includes("/") || dshCommand.includes("\\")) return existsSync(dshCommand);
	try {
		return (platform === "win32" ? await run("where", [dshCommand]) : await run("sh", ["-lc", `command -v ${dshCommand}`])).code === 0;
	} catch {
		return false;
	}
}
/**
* Write the launcher script and place the desktop icon for the current
* platform. Refreshing is idempotent: rerunning overwrites both files.
* @param deps - spec resolver plus test seams.
* @returns the icon path and any non-fatal warning.
*/
async function createDesktopShortcut(deps) {
	const spec = deps.resolveSpec();
	const platform = toLauncherPlatform(deps.platform ?? process.platform);
	const home = deps.homeDir ?? homedir();
	const run = deps.run ?? defaultRunner;
	const scriptsDir = join(home, ".dsh", "desktop-launcher");
	await mkdir(scriptsDir, { recursive: true });
	const launcherPath = join(scriptsDir, scriptFileName(platform));
	await writeFile(launcherPath, "﻿" + renderLauncherScript(platform, spec), { mode: 493 });
	let iconIco;
	let iconPng;
	const iconSource = resolveIconSource(spec.iconPath, deps.iconSource);
	if (iconSource !== void 0) {
		iconIco = join(scriptsDir, "dsh.ico");
		await copyFile(iconSource, iconIco);
		if (/\.png$/i.test(iconSource)) {
			iconPng = join(scriptsDir, "dsh.png");
			await copyFile(iconSource, iconPng);
		} else if (bundledPngPath !== void 0 && existsSync(bundledPngPath)) {
			iconPng = join(scriptsDir, "dsh.png");
			await copyFile(bundledPngPath, iconPng);
		}
	}
	const desktopDir = resolveDesktopDir(home, platform);
	await mkdir(desktopDir, { recursive: true });
	const iconPath = join(desktopDir, desktopFileName(platform));
	let warning;
	if (!await probeDsh(platform, run, spec.dshCommand)) warning = `dsh command "${spec.dshCommand}" was not found on PATH; the launcher shows a message when run`;
	if (platform === "win32") {
		const installerPath = join(scriptsDir, "install-shortcut.ps1");
		await writeFile(installerPath, renderShortcutInstaller({
			launcherPath,
			desktopPath: iconPath,
			homeDir: home,
			iconLocation: iconIco ?? "powershell.exe,0"
		}));
		const result = await run("powershell", [
			"-NoProfile",
			"-ExecutionPolicy",
			"Bypass",
			"-File",
			installerPath
		]);
		if (result.code !== 0) throw new Error(`shortcut creation failed: ${result.stderr}`);
	} else if (platform === "darwin") await writeFile(iconPath, renderLauncherScript(platform, spec), { mode: 493 });
	else {
		await writeFile(iconPath, renderDesktopEntry(launcherPath, iconPng ?? iconIco), { mode: 493 });
		await chmod(launcherPath, 493);
		const trust = await run("gio", [
			"set",
			iconPath,
			"metadata::trusted",
			"true"
		]);
		if (trust.code !== 0) warning = `desktop entry created but not marked trusted: ${trust.stderr}`;
	}
	return {
		ok: true,
		path: iconPath,
		platform,
		...warning === void 0 ? {} : { warning }
	};
}
/**
 * Resolve the DSH_HOME embedded into autostart scripts: the explicit dep,
 * then the ambient variable of the running host (the value that demonstrably
 * works), then the conventional default location.
 */
function resolveDshHome(deps) {
	if (deps.dshHome !== void 0 && deps.dshHome !== "") return deps.dshHome;
	const ambient = process.env.DSH_HOME;
	if (ambient !== void 0 && ambient.trim() !== "") return ambient;
	return join(deps.homeDir ?? homedir(), ".dsh");
}
/** Absolute path of the silent autostart script for the given platform/home. */
function autostartScriptPath(platform, home) {
	return join(home, ".dsh", "desktop-launcher", autostartFileName(platform));
}
/**
 * Read the current boot-autostart registration state.
 * @param deps - spec resolver plus test seams.
 * @returns the status snapshot.
 */
async function getAutostartStatus(deps) {
	const platform = toLauncherPlatform(deps.platform ?? process.platform);
	const home = deps.homeDir ?? homedir();
	const entryPath = autostartEntryPath(platform, home);
	const scriptPath = autostartScriptPath(platform, home);
	return {
		ok: true,
		platform,
		registered: existsSync(entryPath),
		entryPath,
		scriptPath
	};
}
/**
 * Enable boot autostart: write the silent script from the live spec (with
 * the embedded DSH_HOME) and register the per-user login entry. Idempotent —
 * rerunning refreshes the script in place so url/profile changes propagate.
 */
async function enableAutostart(deps) {
	const spec = deps.resolveSpec();
	const platform = toLauncherPlatform(deps.platform ?? process.platform);
	const home = deps.homeDir ?? homedir();
	const run = deps.run ?? defaultRunner;
	const dshHome = resolveDshHome(deps);
	const scriptsDir = join(home, ".dsh", "desktop-launcher");
	await mkdir(scriptsDir, { recursive: true });
	const scriptPath = autostartScriptPath(platform, home);
	if (platform === "win32") await writeFile(scriptPath, "﻿" + renderAutostartScript(platform, spec, dshHome), { mode: 493 });
	else {
		await writeFile(scriptPath, renderAutostartScript(platform, spec, dshHome), { mode: 493 });
		await chmod(scriptPath, 493);
	}
	const entryPath = autostartEntryPath(platform, home);
	if (platform === "win32") {
		const icon = join(scriptsDir, "dsh.ico");
		const installerPath = join(scriptsDir, "install-autostart.ps1");
		await writeFile(installerPath, renderAutostartInstaller({
			autostartScriptPath: scriptPath,
			entryPath,
			homeDir: home,
			iconLocation: existsSync(icon) ? icon : "powershell.exe,0"
		}));
		const result = await run("powershell", [
			"-NoProfile",
			"-ExecutionPolicy",
			"Bypass",
			"-File",
			installerPath
		]);
		if (result.code !== 0) throw new Error(`autostart registration failed: ${result.stderr}`);
	} else if (platform === "darwin") {
		await mkdir(join(home, "Library", "LaunchAgents"), { recursive: true });
		await writeFile(entryPath, renderAutostartPlist(scriptPath, `${scriptsDir}/autostart.out.log`));
		await run("launchctl", ["unload", entryPath]).catch(() => ({ code: null, stderr: "" }));
		const loaded = await run("launchctl", ["load", entryPath]);
		if (loaded.code !== 0) throw new Error(`launchctl load failed: ${loaded.stderr}`);
	} else {
		await mkdir(join(home, ".config", "autostart"), { recursive: true });
		await writeFile(entryPath, renderAutostartDesktopEntry(scriptPath));
	}
	return {
		ok: true,
		platform,
		registered: true,
		entryPath,
		scriptPath
	};
}
/**
 * Disable boot autostart: remove the per-user login entry (the silent script
 * stays behind harmlessly and is refreshed on the next enable).
 */
async function disableAutostart(deps) {
	const platform = toLauncherPlatform(deps.platform ?? process.platform);
	const home = deps.homeDir ?? homedir();
	const run = deps.run ?? defaultRunner;
	const entryPath = autostartEntryPath(platform, home);
	if (existsSync(entryPath)) {
		if (platform === "darwin") await run("launchctl", ["unload", entryPath]).catch(() => ({ code: null, stderr: "" }));
		await rm(entryPath, { force: true });
	}
	return {
		ok: true,
		platform,
		registered: false,
		entryPath,
		scriptPath: autostartScriptPath(platform, home)
	};
}
/** Read one request body as UTF-8 text (bounded at 64 KiB). */
function readBody(req) {
	return new Promise((resolve, reject) => {
		const chunks = [];
		let size = 0;
		req.on("data", (chunk) => {
			size += chunk.length;
			if (size > 65536) {
				reject(new Error("request body too large"));
				req.destroy();
				return;
			}
			chunks.push(chunk);
		});
		req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
		req.on("error", reject);
	});
}
/**
* Build the /api/dsh-desktop-launcher route family.
* @param deps - spec resolver plus test seams.
* @returns the routes.
*/
function makeRoutes(deps) {
	return { routes: [{
		kind: "exact",
		path: LAUNCHER_API.create,
		handler: async (req, res) => {
			if (!isLoopbackRequest(req)) {
				writeJson$1(res, 403, { error: "forbidden: loopback-only" });
				return;
			}
			if ((req.method ?? "GET") !== "POST") {
				writeJson$1(res, 405, { error: `method not allowed: ${req.method}` });
				return;
			}
			try {
				writeJson$1(res, 200, { result: await createDesktopShortcut(deps) });
			} catch (error) {
				writeJson$1(res, 500, { error: error instanceof Error ? error.message : String(error) });
			}
		}
	}, {
		kind: "exact",
		path: LAUNCHER_API.autostart,
		handler: async (req, res) => {
			if (!isLoopbackRequest(req)) {
				writeJson$1(res, 403, { error: "forbidden: loopback-only" });
				return;
			}
			try {
				if ((req.method ?? "GET") === "GET") {
					writeJson$1(res, 200, await getAutostartStatus(deps));
					return;
				}
				if ((req.method ?? "GET") !== "POST") {
					writeJson$1(res, 405, { error: `method not allowed: ${req.method}` });
					return;
				}
				const raw = await readBody(req);
				let parsed;
				try {
					const body = JSON.parse(raw);
					if (typeof body === "object" && body !== null && typeof body.enabled === "boolean") parsed = body;
				} catch {}
				if (parsed === void 0) {
					writeJson$1(res, 400, { error: 'expected JSON body {"enabled": boolean}' });
					return;
				}
				writeJson$1(res, 200, parsed.enabled ? await enableAutostart(deps) : await disableAutostart(deps));
			} catch (error) {
				writeJson$1(res, 500, { error: error instanceof Error ? error.message : String(error) });
			}
		}
	}] };
}
/** One JSON response. */
function writeJson(res, status, body) {
	const payload = JSON.stringify(body);
	res.writeHead(status, {
		"content-type": "application/json; charset=utf-8",
		"referrer-policy": "no-referrer"
	});
	res.end(payload);
}
/**
* Build the shutdown route.
* @param deps - fence + exit seam (and an optional schedule seam for tests).
* @returns the exact route to register on webServer.
*/
function makeShutdownRoute(deps) {
	const schedule = deps.schedule ?? ((fn, ms) => setTimeout(fn, ms));
	return {
		kind: "exact",
		path: LAUNCHER_API.shutdown,
		handler: async (req, res) => {
			if (req.method !== "POST") {
				res.writeHead(405, { "content-type": "text/plain; charset=utf-8" });
				res.end("method not allowed");
				return;
			}
			if (!deps.fence(req)) {
				writeJson(res, 403, {
					ok: false,
					code: "forbidden"
				});
				return;
			}
			writeJson(res, 200, { ok: true });
			schedule(() => deps.requestExit(0), 80);
		}
	};
}
//#endregion
//#region src/mount-once.ts
/**
* Host single-instance guard shared by the plugin family. The family bundle
* (dsh-web-ui-all / dsh-skins) namespaces every child row id (web-ui-*), so
* the loader accepts a standalone install of the same package side by side;
* without this guard the second instance would still re-register the same
* webserver routes, tools, settings namespaces, and system-prompt sections
* and fail the boot. mountOnce makes the second host apply a no-op for the
* lifetime of the first instance (the browser half is already deduped by
* package name in the client module host).
*
* The registry rides a global symbol so two module instances of the same
* package (npm copy vs repository link) still share one verdict. cordis
* `ctx.effect` runs its callback immediately and treats the callback's
* return value as the fiber disposer, so the unmarker is returned, not run.
*/
const MOUNTED = Symbol.for("dsh-web-ui.mounted-plugins");
function mountedSet() {
	const registry = globalThis;
	return registry[MOUNTED] ??= /* @__PURE__ */ new Set();
}
/**
* Wrap a cordis plugin apply so the package runs at most once per process.
* The first mount registers normally and unmarks when its fiber disposes;
* any later mount of the same package name is a no-op.
* @param packageName - npm package identity shared by every install source.
* @param fn - the original plugin apply.
* @returns an apply of the same shape.
*/
function mountOnce(packageName, fn) {
	return ((...args) => {
		const mounted = mountedSet();
		if (mounted.has(packageName)) return;
		mounted.add(packageName);
		args[0]?.effect?.(() => () => {
			mounted.delete(packageName);
		});
		return fn(...args);
	});
}
//#endregion
//#region src/index.ts
/** Stable cordis plugin name. */
const name = "desktop-launcher";
/** Services required before the launcher surfaces can mount. */
const inject = ["webServer", "systemPrompt"];
/**
* Settings namespace of the desktop-launcher capability — the section the
* web settings surface edits. Spelled here rather than imported so the
* browser half can spell the same value without depending on a Host package.
*/
const DESKTOP_LAUNCHER_SETTINGS_NAMESPACE = settingsNamespace("desktop-launcher");
const Config = z.object({
	announceToAgent: z.boolean().default(true),
	enabled: z.boolean().default(true),
	dshCommand: z.string().default("dsh"),
	url: z.string().default(DEFAULT_URL),
	profile: z.string().default(""),
	iconPath: z.string().default(""),
	confirmShutdown: z.boolean().default(true),
	autostart: z.boolean().default(false)
});
/** Schema default, re-read for hand-built test contexts (the loader applies them normally). */
const DEFAULT_ANNOUNCE = true;
/** Order of the announcement section within the tool-guidance band. */
const SECTION_ORDER = 210;
/** Model-facing announcement: plugin presence, capabilities, and limits. */
const DESKTOP_LAUNCHER_GUIDANCE = "本机已安装 dsh-desktop-launcher 插件（DSH 桌面启动器 + 开机自启 + 一键关机）：设置 → 插件配置 → Web UI 插件 卡片内「创建桌面图标」可生成一键启动图标（Windows .lnk / macOS .command / Linux .desktop），双击即启动 dsh web 并打开 Web GUI；「开机自启动」开关把当前用户登录项写入系统（Windows 启动文件夹 / macOS LaunchAgent / Linux XDG autostart），登录后静默启动服务、就绪后打开浏览器；脚本落在 ~/.dsh/desktop-launcher/autostart.ps1，日志在同目录 autostart.log；可配置 dshCommand / url / profile。启动脚本内置单实例保护：端口已被占用时绝不重复拉起第二个实例（避免 EADDRINUSE 崩溃），探测绕过系统代理。界面右下角还有关机样式浮动按钮，点击弹出确认框，确认后请求宿主进程优雅退出（经 ctx.appExit，先回收插件树再退出；无 appExit 时回退 process.exit(0)）。限制：图标、自启与关机路由均仅限 loopback，退出会终止 dsh web 进程，正在运行的会话/任务可能中断。用户提到「桌面图标 / 快捷方式 / 一键启动 dsh / 开机自启 / 自启动 / 关机 / 退出 DeepSeek Harness」时即指本插件，请据此协作。";
/**
* Mount the route and announcement, gated on the composition entry config
* (and the live settings value once the web settings surface is served).
* @param ctx - host plugin context carrying webServer/systemPrompt.
* @param config - resolved plugin config (schema defaults applied by the loader).
*/
const apply = mountOnce("@linxin666/dsh-desktop-launcher", applyImpl);
function applyImpl(ctx, config) {
	let current = () => config ?? {};
	let disposeRoutes;
	let disposeShutdownRoute;
	let disposeSection;
	/** Ask the launcher for a bounded exit; fall back to a direct exit. */
	const requestExit = (code) => {
		const exit = ctx.get("appExit");
		if (exit !== void 0) {
			exit(code);
			return;
		}
		process.exit(code);
	};
	/** The live launcher spec resolver shared by routes and autostart sync. */
	const resolveSpec = () => resolveLauncherSpec(current());
	/**
	 * Reconcile the OS-level autostart entry with the configured desire.
	 * Never throws: a failing registration must not take the plugin down —
	 * the settings card reports live state through the status endpoint.
	 */
	/**
	 * Reconcile the OS-level autostart entry with the configured desire.
	 * Never throws: a failing registration must not take the plugin down —
	 * the settings card reports live state through the status endpoint.
	 * @param desired - the wanted registration state; the master switch wins,
	 * so a disabled plugin always reports false.
	 */
	const syncAutostart = async (desired) => {
		try {
			const status = await getAutostartStatus({ resolveSpec });
			if (desired && !status.registered) await enableAutostart({ resolveSpec });
			else if (!desired && status.registered) await disableAutostart({ resolveSpec });
		} catch (error) {
			console.warn("[dsh-desktop-launcher] autostart sync failed:", error instanceof Error ? error.message : String(error));
		}
	};
	const sync = () => {
		if (disposeSection !== void 0) {
			disposeSection();
			disposeSection = void 0;
		}
		if (disposeRoutes !== void 0) {
			disposeRoutes();
			disposeRoutes = void 0;
		}
		if (disposeShutdownRoute !== void 0) {
			disposeShutdownRoute();
			disposeShutdownRoute = void 0;
		}
		const value = current();
		if ((value.enabled ?? true) === false) {
			// Master switch wins: a disabled plugin never leaves a login entry
			// behind pointing at scripts it no longer maintains.
			void syncAutostart(false);
			return;
		}
		disposeRoutes = ctx.effect(() => {
			const disposers = makeRoutes({ resolveSpec }).routes.map((route) => ctx.webServer.register(route));
			return () => {
				for (const dispose of disposers) dispose();
			};
		}, "dsh-desktop-launcher: routes");
		disposeShutdownRoute = ctx.effect(() => ctx.webServer.register(makeShutdownRoute({
			fence: isLoopbackRequest,
			requestExit
		})), "dsh-desktop-launcher: shutdown route");
		if ((value.announceToAgent ?? DEFAULT_ANNOUNCE) !== false) disposeSection = ctx.systemPrompt.section({
			name: "plugin:dsh-desktop-launcher",
			order: SECTION_ORDER,
			text: DESKTOP_LAUNCHER_GUIDANCE
		});
		void syncAutostart((value.autostart ?? false) === true);
	};
	installSettingsSection(ctx, DESKTOP_LAUNCHER_SETTINGS_NAMESPACE, Config, config ?? {}, {
		setSource: (source) => {
			current = source;
			sync();
		},
		onChange: sync
	});
	sync();
}
//#endregion
export { Config, DESKTOP_LAUNCHER_GUIDANCE, DESKTOP_LAUNCHER_SETTINGS_NAMESPACE, apply, inject, name };
