/**
 * Pure autostart-registration generation: entry paths per platform plus the
 * installer/uninstaller bodies. No filesystem or process access here — the
 * route layer (routes.ts) performs the writes through injectable seams so
 * everything stays testable without touching disk.
 */

import type { LauncherPlatform } from './launcher.ts'
import { psSingle } from './quote.ts'

/** Where the per-user boot-autostart entry lives for one platform. */
export function autostartDir(platform: LauncherPlatform, home: string): string {
  switch (platform) {
    case 'win32': {
      const appdata = process.env.APPDATA && process.env.APPDATA.trim() !== '' ? process.env.APPDATA : `${home}\\AppData\\Roaming`
      return `${appdata}\\Microsoft\\Windows\\Start Menu\\Programs\\Startup`
    }
    case 'darwin': return `${home}/Library/LaunchAgents`
    case 'linux': return `${home}/.config/autostart`
  }
}

/**
 * The user-visible autostart entry name: a Startup-folder .lnk on Windows,
 * a LaunchAgent plist on macOS, an XDG autostart .desktop on Linux.
 */
export function autostartEntryName(platform: LauncherPlatform): string {
  switch (platform) {
    case 'win32': return 'DeepSeek-Harness.lnk'
    case 'darwin': return 'com.deepseek-harness.web.plist'
    case 'linux': return 'deepseek-harness-autostart.desktop'
  }
}

/** Full path of the autostart entry for one platform and home. */
export function autostartEntryPath(platform: LauncherPlatform, home: string): string {
  const separator = platform === 'win32' ? '\\' : '/'
  return `${autostartDir(platform, home)}${separator}${autostartEntryName(platform)}`
}

/**
 * Render the Windows autostart installer: a PowerShell script that creates
 * the Startup-folder .lnk pointing at the silent autostart.ps1, run hidden
 * by the host. Same COM mechanism as the desktop shortcut installer.
 * @param opts - the silent script and entry paths plus the icon spec.
 * @returns the installer body.
 */
export function renderAutostartInstaller(opts: {
  /** Absolute path of autostart.ps1. */
  autostartScriptPath: string
  /** Absolute path of the Startup-folder .lnk to create. */
  entryPath: string
  /** Working directory of the shortcut. */
  homeDir: string
  /** Icon the entry shows (an .ico/.png path, or a shell-exe icon spec). */
  iconLocation: string
}): string {
  const { autostartScriptPath, entryPath, homeDir, iconLocation } = opts
  return [
    '# DSH autostart installer (generated by dsh-desktop-launcher)',
    "$ErrorActionPreference = 'Stop'",
    '$ws = New-Object -ComObject WScript.Shell',
    `$shortcut = $ws.CreateShortcut(${psSingle(entryPath)})`,
    `$shortcut.TargetPath = ${psSingle('powershell.exe')}`,
    `$shortcut.Arguments = ${psSingle(`-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ${autostartScriptPath}`)}`,
    `$shortcut.WorkingDirectory = ${psSingle(homeDir)}`,
    `$shortcut.IconLocation = ${psSingle(iconLocation)}`,
    `$shortcut.Description = ${psSingle('Start DeepSeek Harness Web GUI at login')}`,
    '$shortcut.Save()',
    '',
  ].join('\n')
}

/**
 * Render the macOS LaunchAgent plist body running the silent script at
 * login (Aqua session).
 * @param autostartScriptPath - absolute path of autostart.command.
 * @param logPath - stdout/stderr capture next to the script.
 * @returns the plist body.
 */
export function renderAutostartPlist(autostartScriptPath: string, logPath: string): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    '  <key>Label</key>',
    '  <string>com.deepseek-harness.web</string>',
    '  <key>ProgramArguments</key>',
    '  <array>',
    '    <string>/bin/bash</string>',
    `    <string>${autostartScriptPath}</string>`,
    '  </array>',
    '  <key>RunAtLoad</key>',
    '  <true/>',
    '  <key>StandardOutPath</key>',
    `  <string>${logPath}</string>`,
    '  <key>StandardErrorPath</key>',
    `  <string>${logPath}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n')
}

/**
 * Render the Linux XDG autostart desktop entry running the silent script.
 * @param autostartScriptPath - absolute path of autostart.sh.
 * @returns the .desktop body.
 */
export function renderAutostartDesktopEntry(autostartScriptPath: string): string {
  return [
    '[Desktop Entry]',
    'Type=Application',
    'Version=1.0',
    'Name=DeepSeek Harness',
    'Comment=Start DeepSeek Harness Web GUI at login',
    `Exec="${autostartScriptPath}"`,
    'Terminal=false',
    'X-GNOME-Autostart-enabled=true',
    'Categories=Development;',
    '',
  ].join('\n')
}
