/**
 * Pure launcher generation: the PowerShell / POSIX launcher bodies, the
 * Windows shortcut installer, and the desktop file names for the three
 * supported platforms. No filesystem or process access — everything here is
 * testable without touching disk.
 */

/** Desktop platforms the launcher can generate an icon for. */
export type LauncherPlatform = 'win32' | 'darwin' | 'linux'

/** Launcher behavior, resolved from plugin config. */
export interface LauncherSpec {
  /** Command that starts dsh (must be on PATH when the launcher runs). */
  dshCommand: string
  /** Base URL of the dsh web GUI. */
  url: string
  /** Optional profile passed as `dsh web --profile <profile>`. */
  profile?: string
  /** Optional icon file (.ico/.png) for the desktop icon; empty uses the bundled dsh icon. */
  iconPath?: string
}

/** Default dsh command. */
export const DEFAULT_DSH_COMMAND = 'dsh'

/** Default GUI URL. */
export const DEFAULT_URL = 'http://127.0.0.1:3080'

/**
 * Fill defaults from a partial config (schema defaults may be absent in
 * hand-built test contexts). An empty profile means "no --profile flag".
 * @param config - partial launcher config.
 * @returns the resolved spec.
 */
export function resolveLauncherSpec(config: {
  dshCommand?: string
  url?: string
  profile?: string
  iconPath?: string
}): LauncherSpec {
  return {
    dshCommand: config.dshCommand ?? DEFAULT_DSH_COMMAND,
    url: config.url ?? DEFAULT_URL,
    ...(config.profile === undefined || config.profile === '' ? {} : { profile: config.profile }),
    ...(config.iconPath === undefined || config.iconPath === '' ? {} : { iconPath: config.iconPath }),
  }
}

/** File name of the launcher script under ~/.dsh/desktop-launcher/. */
export function scriptFileName(platform: LauncherPlatform): string {
  switch (platform) {
    case 'win32': return 'launcher.ps1'
    case 'darwin': return 'launcher.command'
    case 'linux': return 'launcher.sh'
  }
}

/** File name of the silent boot-autostart script under ~/.dsh/desktop-launcher/. */
export function autostartFileName(platform: LauncherPlatform): string {
  switch (platform) {
    case 'win32': return 'autostart.ps1'
    case 'darwin': return 'autostart.command'
    case 'linux': return 'autostart.sh'
  }
}

/** File name of the boot-autostart registration entry (Startup folder .lnk / LaunchAgent plist / XDG autostart .desktop). */
export function autostartEntryFileName(platform: LauncherPlatform): string {
  switch (platform) {
    case 'win32': return 'DeepSeek-Harness.lnk'
    case 'darwin': return 'com.deepseek-harness.web.plist'
    case 'linux': return 'deepseek-harness-autostart.desktop'
  }
}

/** File name of the icon placed on the Desktop. */
export function desktopFileName(platform: LauncherPlatform): string {
  switch (platform) {
    case 'win32': return 'DeepSeek-Harness.lnk'
    case 'darwin': return 'DeepSeek-Harness.command'
    case 'linux': return 'deepseek-harness.desktop'
  }
}

import { psSingle, shSingle } from './quote.ts'

/**
 * Shared PowerShell prologue: spec-derived probe constants plus the
 * two-stage readiness probe. Stage 1 is a raw TCP connect — immune to
 * system-proxy state, which is what broke boot launches before: a proxy
 * client that was not ready yet made an HTTP-only probe fail, so a second
 * dsh web got spawned and crashed with EADDRINUSE while the first one held
 * the port without serving. Stage 2 is HTTP readiness with an explicit null
 * proxy so localhost never rides a system proxy regardless of configuration.
 */
const POWERSHELL_PROBE_LINES = [
  '$uri = [Uri]$url',
  '$probeHost = $uri.Host',
  '$probePort = $uri.Port',
  '',
  'function Test-DshPort {',
  '  $client = New-Object System.Net.Sockets.TcpClient',
  '  try {',
  '    $connect = $client.ConnectAsync($probeHost, $probePort)',
  '    if (-not $connect.Wait(800)) { return $false }',
  '    return $client.Connected',
  '  } catch {',
  '    return $false',
  '  } finally {',
  '    $client.Dispose()',
  '  }',
  '}',
  '',
  'function Test-DshHttp {',
  '  try {',
  '    $request = [System.Net.HttpWebRequest]::Create($url)',
  '    $request.Proxy = $null',
  '    $request.Timeout = 2000',
  '    $request.ReadWriteTimeout = 2000',
  '    $response = $request.GetResponse()',
  '    $code = [int]$response.StatusCode',
  '    $response.Close()',
  '    return $code -ge 200 -and $code -lt 500',
  '  } catch {',
  '    return $false',
  '  }',
  '}',
]

/** PowerShell launcher: shows a DeepSeek Harness styled popup while it probes, starts dsh hidden, waits for the GUI. */
function renderPowerShell(spec: LauncherSpec): string {
  return [
    '# DeepSeek Harness launcher (generated by dsh-desktop-launcher)',
    "$ErrorActionPreference = 'SilentlyContinue'",
    `$dshCommand = ${psSingle(spec.dshCommand)}`,
    `$url = ${psSingle(spec.url)}`,
    `$profile = ${psSingle(spec.profile ?? '')}`,
    ...POWERSHELL_PROBE_LINES,
    '',
    'if (Test-DshHttp) {',
    '  Start-Process $url',
    '  exit 0',
    '}',
    '',
    '$command = Get-Command $dshCommand -ErrorAction SilentlyContinue',
    '$dshMissing = ($null -eq $command)',
    '',
    '# ---- startup popup: borderless WPF window in DeepSeek Harness style ----',
    'Add-Type -AssemblyName PresentationFramework',
    "[xml]$popupXaml = @'",
    '<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
    '        Width="400" SizeToContent="Height" WindowStyle="None"',
    '        AllowsTransparency="True" Background="Transparent" ShowInTaskbar="False"',
    '        Topmost="True" WindowStartupLocation="CenterScreen">',
    '  <Border CornerRadius="16" Background="#1B1E27" Padding="22,20">',
    '    <Border.Effect>',
    '      <DropShadowEffect Color="#000000" BlurRadius="26" ShadowDepth="0" Opacity="0.5"/>',
    '    </Border.Effect>',
    '    <StackPanel Orientation="Horizontal">',
    '      <Border Width="56" Height="56" CornerRadius="14" Background="#FFFFFF" VerticalAlignment="Center">',
    '        <Image x:Name="IconImage" Width="56" Height="56" Stretch="Uniform"/>',
    '      </Border>',
    '      <StackPanel Margin="16,0,0,0" VerticalAlignment="Center">',
    '        <TextBlock Text="DeepSeek Harness" FontSize="16" FontWeight="SemiBold" Foreground="#F2F3F5"/>',
    '        <StackPanel Orientation="Horizontal" Margin="0,7,0,0">',
    '          <Ellipse x:Name="Spinner" Width="14" Height="14" Stroke="#4D6BFE" StrokeThickness="2"',
    '                   StrokeDashArray="1.6 2.4" RenderTransformOrigin="0.5,0.5">',
    '            <Ellipse.RenderTransform>',
    '              <RotateTransform x:Name="SpinnerRotate" Angle="0"/>',
    '            </Ellipse.RenderTransform>',
    '            <Ellipse.Triggers>',
    '              <EventTrigger RoutedEvent="Ellipse.Loaded">',
    '                <BeginStoryboard>',
    '                  <Storyboard RepeatBehavior="Forever">',
    '                    <DoubleAnimation Storyboard.TargetName="SpinnerRotate" Storyboard.TargetProperty="Angle"',
    '                                     From="0" To="360" Duration="0:0:0.9"/>',
    '                  </Storyboard>',
    '                </BeginStoryboard>',
    '              </EventTrigger>',
    '            </Ellipse.Triggers>',
    '          </Ellipse>',
    '          <TextBlock x:Name="StatusText" Text="正在启动…" FontSize="12" Foreground="#9BA1B0"',
    '                     Margin="9,0,0,0" VerticalAlignment="Center"/>',
    '        </StackPanel>',
    '        <TextBlock x:Name="DetailText" Text="正在准备环境" FontSize="11" Foreground="#6B7280"',
    '                   Margin="0,5,0,0" TextWrapping="Wrap" MaxWidth="280"/>',
    '        <Button x:Name="CloseButton" Content="确定" Visibility="Collapsed" Margin="0,10,0,0"',
    '                HorizontalAlignment="Left" Padding="14,5" FontSize="12" Foreground="#FFFFFF"',
    '                Background="#4D6BFE" BorderThickness="0" Cursor="Hand">',
    '          <Button.Resources>',
    '            <Style TargetType="Button">',
    '              <Setter Property="Template">',
    '                <Setter.Value>',
    '                  <ControlTemplate TargetType="Button">',
    '                    <Border x:Name="Bd" Background="{TemplateBinding Background}" CornerRadius="8"',
    '                            Padding="{TemplateBinding Padding}">',
    '                      <ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/>',
    '                    </Border>',
    '                    <ControlTemplate.Triggers>',
    '                      <Trigger Property="IsMouseOver" Value="True">',
    '                        <Setter TargetName="Bd" Property="Background" Value="#5B77FF"/>',
    '                      </Trigger>',
    '                    </ControlTemplate.Triggers>',
    '                  </ControlTemplate>',
    '                </Setter.Value>',
    '              </Style>',
    '            </Button.Resources>',
    '          </Button>',
    '        </StackPanel>',
    '      </StackPanel>',
    '    </StackPanel>',
    '  </Border>',
    '</Window>',
    "'@",
    '',
    '$popup = [System.Windows.Markup.XamlReader]::Load((New-Object System.Xml.XmlNodeReader $popupXaml))',
    '$iconImage = $popup.FindName(\'IconImage\')',
    '$iconPath = Join-Path $PSScriptRoot \'dsh.png\'',
    "if (-not (Test-Path $iconPath)) { $iconPath = Join-Path $PSScriptRoot 'dsh.ico' }",
    'if (Test-Path $iconPath) { $iconImage.Source = New-Object System.Windows.Media.Imaging.BitmapImage([uri]$iconPath) }',
    '$statusText = $popup.FindName(\'StatusText\')',
    '$detailText = $popup.FindName(\'DetailText\')',
    '$closeButton = $popup.FindName(\'CloseButton\')',
    '',
    'function Pump-Popup {',
    '  [System.Windows.Threading.Dispatcher]::CurrentDispatcher.Invoke([Action]{}, [System.Windows.Threading.DispatcherPriority]::Background) | Out-Null',
    '}',
    '',
    '$closeButton.Add_Click({ $popup.Close() })',
    '',
    'function Show-PopupError($status, $detail) {',
    '  $statusText.Text = $status',
    '  $statusText.Foreground = New-Object System.Windows.Media.SolidColorBrush([System.Windows.Media.Color]::FromRgb(0xE5, 0x4D, 0x4D))',
    '  $detailText.Text = $detail',
    "  $closeButton.Visibility = 'Visible'",
    '  $popup.Show()',
    '  while ($popup.IsVisible) {',
    '    Start-Sleep -Milliseconds 100',
    '    Pump-Popup',
    '  }',
    '}',
    '',
    'if ($dshMissing) {',
    "  Show-PopupError '启动失败' (\"找不到 dsh 命令：\" + $dshCommand)",
    '  exit 1',
    '}',
    '',
    '$popup.Show()',
    '',
    '# Single-instance guard: when something already holds the port, spawning a',
    '# second dsh web would die with EADDRINUSE and leave nothing serving.',
    'if (Test-DshPort) {',
    '  $deadline = (Get-Date).AddSeconds(45)',
    '  while ((Get-Date) -lt $deadline) {',
    '    Start-Sleep -Milliseconds 250',
    '    Pump-Popup',
    '    if (Test-DshHttp) {',
    "      $statusText.Text = '启动完成'",
    '      Pump-Popup',
    '      Start-Sleep -Milliseconds 300',
    '      $popup.Close()',
    '      Start-Process $url',
    '      exit 0',
    '    }',
    '  }',
    '  Show-PopupError \'启动失败\' ("端口 $probePort 已被占用但服务未就绪：可能存在残留的 dsh web 进程，请先结束它再重试。")',
    '  exit 1',
    '}',
    '',
    "$arguments = @('web')",
    "if ($profile -ne '') {",
    "  $arguments += @('--profile', $profile)",
    '}',
    'Start-Process -FilePath $command.Source -ArgumentList $arguments -WindowStyle Hidden',
    '',
    '$deadline = (Get-Date).AddSeconds(90)',
    'while ((Get-Date) -lt $deadline) {',
    '  Start-Sleep -Milliseconds 250',
    '  Pump-Popup',
    '  if (Test-DshHttp) {',
    "    $statusText.Text = '启动完成'",
    "    $detailText.Text = '正在打开浏览器…'",
    '    Pump-Popup',
    '    Start-Sleep -Milliseconds 400',
    '    $popup.Close()',
    '    Start-Process $url',
    '    exit 0',
    '  }',
    '}',
    "Show-PopupError '启动超时' (\"90 秒内未就绪：\" + $url)",
    'exit 1',
    '',
  ].join('\n')
}

/**
 * Render the silent boot-autostart body for Windows: no popup, a bounded
 * append-only log next to the script, an explicit embedded DSH_HOME so a
 * portable home keeps working from a bare login environment, the same
 * single-instance guard as the interactive launcher, and one optional
 * browser tab once the server is actually ready.
 * @param spec - resolved launcher behavior.
 * @param dshHome - DSH_HOME embedded into the script ('' leaves ambient env untouched).
 * @returns the autostart.ps1 body.
 */
export function renderWindowsAutostart(spec: LauncherSpec, dshHome: string): string {
  return [
    '# DeepSeek Harness autostart (generated by dsh-desktop-launcher)',
    '# Silent boot variant of launcher.ps1: no popup, appends to autostart.log.',
    "$ErrorActionPreference = 'SilentlyContinue'",
    `$dshCommand = ${psSingle(spec.dshCommand)}`,
    `$url = ${psSingle(spec.url)}`,
    `$profile = ${psSingle(spec.profile ?? '')}`,
    `$dshHome = ${psSingle(dshHome)}`,
    '$openBrowser = $true',
    '$waitSeconds = 120',
    "$logFile = Join-Path $PSScriptRoot 'autostart.log'",
    ...POWERSHELL_PROBE_LINES,
    '',
    'function Write-Log($message) {',
    '  try {',
    '    $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $message',
    '    Add-Content -LiteralPath $logFile -Value $line -Encoding UTF8',
    '    $item = Get-Item -LiteralPath $logFile -ErrorAction SilentlyContinue',
    '    if ($item -and $item.Length -gt 262144) {',
    '      $tail = Get-Content -LiteralPath $logFile -Tail 200 -Encoding UTF8',
    '      Set-Content -LiteralPath $logFile -Value $tail -Encoding UTF8',
    '    }',
    '  } catch {}',
    '}',
    '',
    '# A portable DSH_HOME must survive a bare login environment: embed the',
    '# value the running host actually used instead of trusting ambient state.',
    "if ($dshHome -ne '') { $env:DSH_HOME = $dshHome }",
    'Write-Log ("autostart tick: url=" + $url)',
    '',
    'if (Test-DshHttp) {',
    '  Write-Log "already serving; nothing to do"',
    '  if ($openBrowser) { Start-Process $url }',
    '  exit 0',
    '}',
    '',
    '# Port held by someone not serving yet: wait instead of spawning a',
    '# duplicate that would crash with EADDRINUSE.',
    'if (Test-DshPort) {',
    '  Write-Log ("port " + $probePort + " already held; waiting for readiness")',
    '  $deadline = (Get-Date).AddSeconds(60)',
    '  while ((Get-Date) -lt $deadline) {',
    '    Start-Sleep -Milliseconds 500',
    '    if (Test-DshHttp) {',
    '      Write-Log "holder became ready"',
    '      if ($openBrowser) { Start-Process $url }',
    '      exit 0',
    '    }',
    '  }',
    '  Write-Log "ERROR: port held but never became ready; not spawning a second instance"',
    '  exit 1',
    '}',
    '',
    '$command = Get-Command $dshCommand -ErrorAction SilentlyContinue',
    'if ($null -eq $command) {',
    '  Write-Log ("ERROR: dsh command not found: " + $dshCommand)',
    '  exit 1',
    '}',
    '',
    "$arguments = @('web')",
    "if ($profile -ne '') {",
    "  $arguments += @('--profile', $profile)",
    '}',
    'Write-Log ("spawning: " + $command.Source + " " + ($arguments -join " "))',
    '$spawned = Start-Process -FilePath $command.Source -ArgumentList $arguments -WindowStyle Hidden -PassThru',
    'if ($spawned) { Write-Log ("spawned pid " + $spawned.Id) }',
    '',
    '$deadline = (Get-Date).AddSeconds($waitSeconds)',
    'while ((Get-Date) -lt $deadline) {',
    '  Start-Sleep -Milliseconds 500',
    '  if (Test-DshHttp) {',
    '    Write-Log "ready"',
    '    if ($openBrowser) { Start-Process $url }',
    '    exit 0',
    '  }',
    '}',
    'Write-Log ("ERROR: not ready within " + $waitSeconds + " seconds")',
    'exit 1',
    '',
  ].join('\n')
}

/** POSIX autostart body shared by macOS and Linux (curl with proxies disabled). */
function renderPosixAutostart(platform: 'darwin' | 'linux', spec: LauncherSpec): string {
  const open = platform === 'darwin' ? 'open' : 'xdg-open'
  return [
    '#!/bin/bash',
    '# DeepSeek Harness autostart (generated by dsh-desktop-launcher)',
    `DASH=${shSingle(spec.dshCommand)}`,
    `URL=${shSingle(spec.url)}`,
    `PROFILE=${shSingle(spec.profile ?? '')}`,
    'OPEN_BROWSER=yes',
    'LOG_FILE="$(dirname "$0")/autostart.log"',
    '',
    'log() { echo "[$(date \'+%Y-%m-%d %H:%M:%S\')] $*" >> "$LOG_FILE"; }',
    'probe_http() { curl --noproxy "*" -fsS --max-time 2 "$URL" >/dev/null 2>&1; }',
    '',
    'log "autostart tick: url=$URL"',
    'if probe_http; then',
    '  log "already serving; nothing to do"',
    '  if [ "$OPEN_BROWSER" = yes ]; then "$open" "$URL"; fi',
    '  exit 0',
    'fi',
    'if command -v lsof >/dev/null 2>&1 && lsof -iTCP -sTCP:LISTEN >/dev/null 2>&1 && echo "$URL" | grep -qE ":[0-9]+$"; then',
    '  PORT="${URL##*:}"',
    '  if lsof -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; then',
    '    log "port $PORT already held; waiting for readiness"',
    '    for i in $(seq 1 120); do',
    '      sleep 0.5',
    '      if probe_http; then',
    '        log "holder became ready"',
    '        if [ "$OPEN_BROWSER" = yes ]; then "$open" "$URL"; fi',
    '        exit 0',
    '      fi',
    '    done',
    '    log "ERROR: port held but never became ready"',
    '    exit 1',
    '  fi',
    'fi',
    'if ! command -v "$DASH" >/dev/null 2>&1; then',
    '  log "ERROR: dsh command not found: $DASH"',
    '  exit 1',
    'fi',
    'if [ -n "$PROFILE" ]; then',
    '  "$DASH" web --profile "$PROFILE" >/dev/null 2>&1 &',
    'else',
    '  "$DASH" web >/dev/null 2>&1 &',
    'fi',
    'for i in $(seq 1 240); do',
    '  if probe_http; then',
    '    log "ready"',
    '    if [ "$OPEN_BROWSER" = yes ]; then "$open" "$URL"; fi',
    '    exit 0',
    '  fi',
    '  sleep 0.5',
    'done',
    'log "ERROR: not ready within 120 seconds"',
    'exit 1',
    '',
  ].join('\n')
}

/**
 * Render the silent boot-autostart body for one platform.
 * @param platform - target desktop platform.
 * @param spec - resolved launcher behavior.
 * @param dshHome - DSH_HOME to embed (used on win32 only).
 * @returns the autostart script body.
 */
export function renderAutostartScript(platform: LauncherPlatform, spec: LauncherSpec, dshHome: string): string {
  switch (platform) {
    case 'win32': return renderWindowsAutostart(spec, dshHome)
    case 'darwin':
    case 'linux': return renderPosixAutostart(platform, spec)
  }
}

/** POSIX launcher (macOS .command / Linux .sh) with the platform open command. */
function renderPosix(platform: 'darwin' | 'linux', spec: LauncherSpec): string {
  const open = platform === 'darwin' ? 'open' : 'xdg-open'
  const alert = platform === 'darwin'
    ? "osascript -e 'display dialog \"dsh command not found: '\"$DASH\"'\" with title \"DSH Launcher\" with icon caution' 2>/dev/null || echo \"dsh command not found: $DASH\" >&2"
    : 'zenity --error --title="DSH Launcher" --text="dsh command not found: $DASH" 2>/dev/null || echo "dsh command not found: $DASH" >&2'
  return [
    '#!/bin/bash',
    '# DSH web launcher (generated by dsh-desktop-launcher)',
    `DASH=${shSingle(spec.dshCommand)}`,
    `URL=${shSingle(spec.url)}`,
    `PROFILE=${shSingle(spec.profile ?? '')}`,
    '',
    'probe() {',
    '  curl --noproxy "*" -fsS --max-time 2 "$URL" >/dev/null 2>&1',
    '}',
    '',
    'if probe; then',
    `  ${open} "$URL"`,
    '  exit 0',
    'fi',
    '',
    'if ! command -v "$DASH" >/dev/null 2>&1; then',
    `  ${alert}`,
    '  exit 1',
    'fi',
    '',
    'if [ -n "$PROFILE" ]; then',
    '  "$DASH" web --profile "$PROFILE" >/dev/null 2>&1 &',
    'else',
    '  "$DASH" web >/dev/null 2>&1 &',
    'fi',
    '',
    'for i in $(seq 1 180); do',
    '  if probe; then',
    `    ${open} "$URL"`,
    '    exit 0',
    '  fi',
    '  sleep 0.5',
    'done',
    '',
    'echo "dsh web did not start within 90 seconds: $URL" >&2',
    'exit 1',
    '',
  ].join('\n')
}

/**
 * Render the launcher script for one platform.
 * @param platform - target desktop platform.
 * @param spec - resolved launcher behavior.
 * @returns the script body.
 */
export function renderLauncherScript(platform: LauncherPlatform, spec: LauncherSpec): string {
  switch (platform) {
    case 'win32': return renderPowerShell(spec)
    case 'darwin':
    case 'linux': return renderPosix(platform, spec)
  }
}

/**
 * Render the Linux desktop entry (the macOS launcher doubles as the desktop
 * file; Windows uses a .lnk created by the installer script).
 * @param launcherPath - absolute path of the launcher script.
 * @returns the .desktop file body.
 */
export function renderDesktopEntry(launcherPath: string, iconPath?: string): string {
  const iconLine = iconPath === undefined ? 'Icon=utilities-terminal' : `Icon=${iconPath}`
  return [
    '[Desktop Entry]',
    'Type=Application',
    'Version=1.0',
    'Name=DeepSeek Harness',
    'Comment=Launch DeepSeek Harness Web GUI',
    `Exec="${launcherPath}"`,
    iconLine,
    'Terminal=true',
    'Categories=Development;',
    '',
  ].join('\n')
}

/**
 * Render the Windows shortcut installer: a PowerShell script that creates
 * the Desktop .lnk pointing at the launcher.ps1, run hidden by the host.
 * @param opts - the launcher, icon, and working-directory paths.
 * @returns the installer body.
 */
export function renderShortcutInstaller(opts: {
  /** Absolute path of launcher.ps1. */
  launcherPath: string
  /** Absolute path of the DSH.lnk to create. */
  desktopPath: string
  /** Working directory of the shortcut (the home dir). */
  homeDir: string
  /** Icon the shortcut shows (an .ico/.png path, or a shell-exe icon spec). */
  iconLocation: string
}): string {
  const { launcherPath, desktopPath, homeDir, iconLocation } = opts
  return [
    '# DSH desktop shortcut installer (generated by dsh-desktop-launcher)',
    "$ErrorActionPreference = 'Stop'",
    '$ws = New-Object -ComObject WScript.Shell',
    `$shortcut = $ws.CreateShortcut(${psSingle(desktopPath)})`,
    `$shortcut.TargetPath = ${psSingle('powershell.exe')}`,
    `$shortcut.Arguments = ${psSingle(`-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ${launcherPath}`)}`,
    `$shortcut.WorkingDirectory = ${psSingle(homeDir)}`,
    `$shortcut.IconLocation = ${psSingle(iconLocation)}`,
    `$shortcut.Description = ${psSingle('Launch DeepSeek Harness Web GUI')}`,
    '$shortcut.Save()',
    '',
  ].join('\n')
}
